version: '3'
services:
  teacher_db:
    image: postgres:15
    ports:
      - 32711:5432 # 32704 внешний порт для подключения к бд
    volumes:
      - /var/lib/telegram_bot:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=bot_data
    networks:
      - teacher_bot
  teacher_bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: teacher_bot
    restart: always
    environment:
      - LOGIN=administrator #токен телеграм бота, можно передать через перемменную окружения
      - PASSWORD=3jf95hjy503ffj
      #- PREFIX="" /route-message
    networks:
      - teacher_bot
networks:
  teacher_bot:
    driver: bridge